access_key_id: 'AKxxxxxxxxxxxxxxxxxxxxxxxxxx'
secret_access_key: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
region: 'ap-northeast-1'
user: "username"
key_path: "/path/to/key.pem"
instance_type: "t2.micro"
vpc_subnet: "subnet-xxxxxxxx"
security_group: "sg-xxxxxxxxx"
key_name: "keyname"
tag_name: "tagname"
image_tag_name: "imagename"
user_data_path: "userdata.txt"
